USE Hacker_Rank;

CREATE TABLE EMPLOYEES(
	ID INT,
	NAME VARCHAR(25),
	SALARY INT
);

INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (1,'Ashley',2340);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (2,'Julia',1198);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (3,'Britney',9009);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (4,'Kristeen',2341);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (5,'Dyana',9990);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (6,'Diana',8011);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (7,'Jenny',2341);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (8,'Christeen',2342);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (9,'Meera',2343);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (10,'Priya',2344);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (11,'Priyanka',2345);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (12,'Paige',2346);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (13,'Jane',2347);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (14,'Belvet',2348);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (15,'Scarlet',2349);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (16,'Salma',9087);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (17,'Amanda',7777);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (18,'Aamina',5500);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (19,'Amina',2570);
INSERT INTO EMPLOYEES(ID,NAME,SALARY) VALUES (20,'Ketty',2007);
