USE Hacker_Rank;
GO

-- sp_help IS EQUIVALENT OF ORACLES'S DESC COMMAND.
--exec sp_help 'table_name_in_single_quote';

CREATE TABLE CITY(
	ID INT,
	NAME VARCHAR(17),
	COUNTRYCODE VARCHAR(3),
	DISTRICT VARCHAR(30),
	POPULATION INT
);
GO
TRUNCATE TABLE CITY
--DATA FOR CITY TABLE
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (6,'Rotterdam','NLD','Zuid-Holland',593321);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (19,'Zaanstad','NLD','Noord-Holland',135621);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (214,'Porto Alegre','BRA','Rio', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (397,'Lauro de Freitas','BRA', NULL, NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (547,'Dobric','BGR','Varna',100399);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (552,'Bujumbura','BDI','Bujumbura',300000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (554,'Santiago de Chile','CHL', NULL, NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (626,'al-Minya','EGY','al-Minya',201360);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (646,'Santa Ana','SLV','Santa', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (762,'Bahir Dar','ETH','Amhara', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (796,'Baguio','PHL','CAR',252386);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (896,'Malungon','PHL','Southern Mindanao', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (904,'Banjul','GMB','Banjul',42326);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (924,'Villa Nueva','GTM','Guatemala', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (990,'Waru','IDN','East Java', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1155,'Latur','IND','Maharashtra',197408);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1222,'Tenali','IND','Andhra Pradesh', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1235,'Tirunelveli','IND','Tamil Nadu', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1256,'Alandur','IND','Tamil Nadu', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1279,'Neyveli','IND','Tamil Nadu', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1293,'Pallavaram','IND','Tamil Nadu', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1350,'Dehri','IND','Bihar',94526);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1383,'Tabriz','IRN','East Azerbaidzan', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1385,'Karaj','IRN','Teheran',940968);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1508,'Bolzano','ITA','Trentino-Alto Adige', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1520,'Cesena','ITA','Emilia-Romagna',89852);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1613,'Neyagawa','JPN','Osaka',257315);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1630,'Ageo','JPN','Saitama',209442);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1661,'Sayama','JPN','Saitama',162472);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1681,'Omuta','JPN','Fukuoka',142889);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1739,'Tokuyama','JPN','Yamaguchi',107078);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1793,'Novi Sad','YUG','Vojvodina', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1857,'Kelowna','CAN','British Colombia', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1895,'Harbin','CHN','Heilongjiang',4289800);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1900,'Changchun','CHN','Jilin',2812000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1913,'Lanzhou','CHN','Gansu',1565800);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1947,'Changzhou','CHN','Jiangsu',530000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2070,'Dezhou','CHN','Shandong',195485);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2081,'Heze','CHN','Shandong',189293);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2111,'Chenzhou','CHN','Hunan',169400);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2153,'Xianning','CHN','Hubei',136811);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2192,'Lhasa','CHN','Tibet',120000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2193,'Lianyuan','CHN','Hunan',118858);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2227,'Xingcheng','CHN','Liaoning',102384);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2273,'Villavicencio','COL','Meta',273140);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2384,'Tong-yong','KOR','Kyongsangnam',131717);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2386,'Yongju','KOR','Kyongsangbuk',131097);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2387,'Chinhae','KOR','Kyongsangnam',125997);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2388,'Sangju','KOR','Kyongsangbuk',124116);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2406,'Herakleion','GRC','Crete',116178);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2440,'Monrovia','LBR','Montserrado',850000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2462,'Lilongwe','MWI','Lilongwe',435964);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2505,'Taza','MAR','Taza-Al Hoceima-Taou', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2555,'Xalapa','MEX','Veracruz',390058);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2602,'Ocosingo','MEX','Chiapas',171495);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2609,'Nogales','MEX','Sonora',159103);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2670,'San Pedro Cholula','MEX', NULL, NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2689,'Palikir','FSM','Pohnpei',8600);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2706,'Tete','MOZ','Tete',101984);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2716,'Sittwe (Akyab)','MMR','Rakhine', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2922,'Carolina','PRI','Carolina',186076);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2967,'Grudziadz','POL','Kujawsko-Pomorskie',102434);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (2972,'Malabo','GNQ','Bioko',40000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3073,'Essen','DEU','Nordrhein-Westfalen',599515);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3169,'Apia','WSM','Upolu',35900);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3198,'Dakar','SEN','Cap-Vert',785071);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3253,'Hama','SYR','Hama',343361);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3288,'Luchou','TWN','Taipei',160516);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3309,'Tanga','TZA','Tanga',137400);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3353,'Sousse','TUN','Sousse',145900);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3377,'Kahramanmaras','TUR','Kahramanmaras',245772);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3430,'Odesa','UKR','Odesa',1011000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3581,'St Petersburg','RUS','Pietari', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3770,'Hanoi','VNM','Hanoi',1410000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3815,'El Paso','USA','Texas', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3878,'Scottsdale','USA','Arizona',202705);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3965,'Corona','USA','California',124966);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3973,'Concord','USA','California',121780);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3977,'Cedar Rapids','USA','Iowa', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (3982,'Coral Springs','USA','Florida', NULL);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (4054,'Fairfield','USA','California',92256);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (4058,'Boulder','USA','Colorado',91238);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (4061,'Fall River','USA','Massachusetts', NULL);

INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (4,'Mazar-e-Sharif','AFG','Balkh',127800);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (11,'Groningen','NLD','Groningen',172701);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (80,'Merlo','ARG','Buenos',Aires);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (89,'San','Isidro','ARG',Buenos);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (91,'Malvinas','Argentinas','ARG',Buenos);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (124,'San','Rafael','ARG',Mendoza);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (128,'Vanadzor','ARM','Lori',172700);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (141,'Geelong','AUS','Victoria',125382);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (142,'Townsville','AUS','Queensland',109914);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (143,'Cairns','AUS','Queensland',92273);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (146,'Sumqayit','AZE','Sumqayit',283000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (150,'Dhaka','BGD','Dhaka',3612850);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (151,'Chittagong','BGD','Chittagong',1392860);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (162,'Dinajpur','BGD','Rajshahi',127815);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (166,'Tangail','BGD','Dhaka',106004);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (168,'Pabna','BGD','Rajshahi',103277);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (304,'Petrolina','BRA','Pernambuco',210540);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (321,'Rio','Grande','BRA',Rio);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (379,'Palmas','BRA','Tocantins',121919);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (431,'Angra','dos','Reis',BRA);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (473,'Stoke-on-Trent','GBR','England',252000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (478,'Aberdeen','GBR','Scotland',213070);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (479,'Northampton','GBR','England',196000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (484,'Luton','GBR','England',183000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (510,'Slough','GBR','England',112000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (521,'Colchester','GBR','England',96063);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (526,'Birkenhead','GBR','England',93087);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (532,'Maidstone','GBR','England',90878);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (540,'Plovdiv','BGR','Plovdiv',342584);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (575,'Punta','Arenas','CHL',Magallanes);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (628,'Qina','EGY','Qina',171275);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (633,'Warraq','al-Arab','EGY',Giza);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (657,'Zaragoza','ESP','Aragonia',603367);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (665,'Vigo','ESP','Galicia',283670);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (673,'Badalona','ESP','Katalonia',209635);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (686,'Terrassa','ESP','Katalonia',168695);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (720,'Kempton','Park','ZAF',Gauteng);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (721,'Alberton','ZAF','Gauteng',410102);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (732,'Klerksdorp','ZAF','North',West);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (738,'Uitenhage','ZAF','Eastern',Cape);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (743,'Brakpan','ZAF','Gauteng',171363);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (784,'Iloilo','PHL','Western',Visayas);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (789,'Iligan','PHL','Central',Mindanao);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (805,'San','Pablo','PHL',Southern);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (811,'Binangonan','PHL','Southern',Tagalog);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (820,'Legazpi','PHL','Bicol',157010);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (858,'Hagonoy','PHL','Central',Luzon);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (865,'San','Jose','PHL',Central);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (886,'Bislig','PHL','Caraga',97860);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (887,'Talavera','PHL','Central',Luzon);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (892,'Capas','PHL','Central',Luzon);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (902,'Libreville','GAB','Estuaire',419000);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (906,'Kutaisi','GEO','Imereti',240900);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (909,'Sohumi','GEO','Abhasia',[Aphazeti]);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (931,'Delmas','HTI','Ouest',240429);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (939,'Jakarta','IDN','Jakarta',Raya);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (941,'Bandung','IDN','West',Java);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (967,'Ciputat','IDN','West',Java);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (981,'Karawang','IDN','West',Java);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (997,'Cianjur','IDN','West',Java);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1002,'Citeureup','IDN','West',Java);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1004,'Klaten','IDN','Central',Java);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1021,'Sawangan','IDN','West',Java);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1032,'Nagpur','IND','Maharashtra',1624752);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1045,'Patna','IND','Bihar',917243);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1046,'Srinagar','IND','Jammu',and);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1060,'Hubli-Dharwad','IND','Karnataka',648298);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1063,'Bareilly','IND','Uttar',Pradesh);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1092,'Bhilai','IND','Chhatisgarh',386159);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1099,'Jamnagar','IND','Gujarat',341637);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1119,'Davangere','IND','Karnataka',266082);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1122,'Bellary','IND','Karnataka',245391);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1126,'Muzaffarpur','IND','Bihar',241107);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1163,'Bally','IND','West',Bengali);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1164,'Bhilwara','IND','Rajasthan',183965);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1195,'Arrah','(Ara)','IND',Bihar);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1201,'Cuddalore','IND','Tamil',Nadu);
INSERT INTO CITY(ID,NAME,COUNTRYCODE,DISTRICT,POPULATION) VALUES (1203,'Dhanbad','IND','Jharkhand',151789);



SELECT * FROM CITY