USE Hacker_Rank;

CREATE TABLE OCCUPATIONS(
   NAME       VARCHAR(20)
  ,OCCUPATION VARCHAR(20)
);

--SELECT * FROM OCCUPATIONS;

INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Ashley','Professor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Samantha','Actor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Julia','Doctor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Britney','Professor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Maria','Professor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Meera','Professor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Priya','Doctor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Priyanka','Professor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Jennifer','Actor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Ketty','Actor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Belvet','Professor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Naomi','Professor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Jane','Singer');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Jenny','Singer');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Kristeen','Singer');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Christeen','Singer');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Eve','Actor');
INSERT INTO OCCUPATIONS(NAME,OCCUPATION) VALUES ('Aamina','Doctor');
