--USE Hacker_Rank;

CREATE TABLE STUDENTS(
   ID    INTEGER  
  ,NAME  VARCHAR(9) 
  ,MARKS INTEGER 
);

SELECT * FROM STUDENTS;

INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (19,'Samantha',87);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (21,'Julia',96);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (11,'Britney',95);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (32,'Kristeen',100);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (12,'Dyana',55);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (13,'Jenny',66);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (14,'Christene',88);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (15,'Meera',24);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (16,'Priya',76);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (17,'Priyanka',77);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (18,'Paige',74);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (19,'Jane',64);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (21,'Belvet',78);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (31,'Scarlet',80);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (41,'Salma',81);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (51,'Amanda',34);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (61,'Heraldo',94);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (71,'Stuart',99);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (81,'Aamina',77);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (76,'Amina',89);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (91,'Vivek',84);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (17,'Evil',79);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (16,'Devil',76);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (34,'Fanny',75);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (38,'Danny',75);
