USE Hacker_Rank;

CREATE TABLE GRADES(
	GRADE INT,
	MIN_MARK INT,
	MAX_MARK INT
);

INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (1,0,9);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (2,10,19);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (3,20,29);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (4,30,39);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (5,40,49);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (6,50,59);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (7,60,69);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (8,70,79);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (9,80,89);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (10,90,100);
