USE Hacker_Rank;

CREATE TABLE DIFFICULTY(
	DIFFICULTY_LEVEL INT,
	SCORE INT
);

INSERT INTO DIFFICULTY(DIFFICULTY_LEVEL,SCORE) VALUES (1,20);
INSERT INTO DIFFICULTY(DIFFICULTY_LEVEL,SCORE) VALUES (2,30);
INSERT INTO DIFFICULTY(DIFFICULTY_LEVEL,SCORE) VALUES (3,40);
INSERT INTO DIFFICULTY(DIFFICULTY_LEVEL,SCORE) VALUES (4,60);
INSERT INTO DIFFICULTY(DIFFICULTY_LEVEL,SCORE) VALUES (5,80);
INSERT INTO DIFFICULTY(DIFFICULTY_LEVEL,SCORE) VALUES (6,100);
INSERT INTO DIFFICULTY(DIFFICULTY_LEVEL,SCORE) VALUES (7,120);
